[phases.setup]
nixPkgs = [
  "python310.withPackages (ps: with ps; [ pip setuptools wheel ])"
]

[phases.install]
cmds = [
  "pip install -r requirements.txt",
  "python download_nltk_data.py"
]

[start]
cmd = "gunicorn app:app"

