[build]
builder = "nixpacks"
buildCommand = "python3.10 pip install -r requirements.txt && python download_nltk_data.py"

[deploy]
startCommand = "gunicorn app:app"
healthcheckPath = "/api/test"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10 
